`default_nettype none
`timescale 1ns/1ns

// AUTO-GENERATED by test/helpers/synth_init.py from `test_strfb`.
// Do not hand-edit. To regenerate:  make synth_kernel KERNEL=test_strfb
//
// program_rom: async read, one logical array; Quartus typically maps the 256x16
// ROM to MLABs or ALM registers (inlined `initial` -- no .mif/.hex).
//
// data_ram: async combinational read + up to 4 independent
// sync write strobes per cycle. That is NOT inferrable as a single M10K (one write
// port); `ramstyle="logic"` plus unrolled writes keep the whole array in
// flip-flops / soft logic so behavior matches Icarus. Do not strip those attributes.
//
// Port shape MATCHES synth/sim_program_rom.sv and synth/sim_data_ram.sv (minus
// the test-only init backdoor). data_ram adds dbg_addr/dbg_dout for FPGA HEX
// readback (synthesis tools cannot hierarchically tap internal mem[]).

module program_rom #(
    parameter ADDR_BITS = 8,
    parameter DATA_BITS = 16,
    parameter NUM_CHANNELS = 1
) (
    input wire clk,
    input wire [ADDR_BITS-1:0] addr [NUM_CHANNELS-1:0],
    output wire [DATA_BITS-1:0] dout [NUM_CHANNELS-1:0]
);
    reg [DATA_BITS-1:0] mem [0:(1<<ADDR_BITS)-1];

    initial begin
        mem[  0] = 16'h9001;
        mem[  1] = 16'hcf0f;
        mem[  2] = 16'hf000;
        mem[  3] = 16'h0000;
        mem[  4] = 16'h0000;
        mem[  5] = 16'h0000;
        mem[  6] = 16'h0000;
        mem[  7] = 16'h0000;
        mem[  8] = 16'h0000;
        mem[  9] = 16'h0000;
        mem[ 10] = 16'h0000;
        mem[ 11] = 16'h0000;
        mem[ 12] = 16'h0000;
        mem[ 13] = 16'h0000;
        mem[ 14] = 16'h0000;
        mem[ 15] = 16'h0000;
        mem[ 16] = 16'h0000;
        mem[ 17] = 16'h0000;
        mem[ 18] = 16'h0000;
        mem[ 19] = 16'h0000;
        mem[ 20] = 16'h0000;
        mem[ 21] = 16'h0000;
        mem[ 22] = 16'h0000;
        mem[ 23] = 16'h0000;
        mem[ 24] = 16'h0000;
        mem[ 25] = 16'h0000;
        mem[ 26] = 16'h0000;
        mem[ 27] = 16'h0000;
        mem[ 28] = 16'h0000;
        mem[ 29] = 16'h0000;
        mem[ 30] = 16'h0000;
        mem[ 31] = 16'h0000;
        mem[ 32] = 16'h0000;
        mem[ 33] = 16'h0000;
        mem[ 34] = 16'h0000;
        mem[ 35] = 16'h0000;
        mem[ 36] = 16'h0000;
        mem[ 37] = 16'h0000;
        mem[ 38] = 16'h0000;
        mem[ 39] = 16'h0000;
        mem[ 40] = 16'h0000;
        mem[ 41] = 16'h0000;
        mem[ 42] = 16'h0000;
        mem[ 43] = 16'h0000;
        mem[ 44] = 16'h0000;
        mem[ 45] = 16'h0000;
        mem[ 46] = 16'h0000;
        mem[ 47] = 16'h0000;
        mem[ 48] = 16'h0000;
        mem[ 49] = 16'h0000;
        mem[ 50] = 16'h0000;
        mem[ 51] = 16'h0000;
        mem[ 52] = 16'h0000;
        mem[ 53] = 16'h0000;
        mem[ 54] = 16'h0000;
        mem[ 55] = 16'h0000;
        mem[ 56] = 16'h0000;
        mem[ 57] = 16'h0000;
        mem[ 58] = 16'h0000;
        mem[ 59] = 16'h0000;
        mem[ 60] = 16'h0000;
        mem[ 61] = 16'h0000;
        mem[ 62] = 16'h0000;
        mem[ 63] = 16'h0000;
        mem[ 64] = 16'h0000;
        mem[ 65] = 16'h0000;
        mem[ 66] = 16'h0000;
        mem[ 67] = 16'h0000;
        mem[ 68] = 16'h0000;
        mem[ 69] = 16'h0000;
        mem[ 70] = 16'h0000;
        mem[ 71] = 16'h0000;
        mem[ 72] = 16'h0000;
        mem[ 73] = 16'h0000;
        mem[ 74] = 16'h0000;
        mem[ 75] = 16'h0000;
        mem[ 76] = 16'h0000;
        mem[ 77] = 16'h0000;
        mem[ 78] = 16'h0000;
        mem[ 79] = 16'h0000;
        mem[ 80] = 16'h0000;
        mem[ 81] = 16'h0000;
        mem[ 82] = 16'h0000;
        mem[ 83] = 16'h0000;
        mem[ 84] = 16'h0000;
        mem[ 85] = 16'h0000;
        mem[ 86] = 16'h0000;
        mem[ 87] = 16'h0000;
        mem[ 88] = 16'h0000;
        mem[ 89] = 16'h0000;
        mem[ 90] = 16'h0000;
        mem[ 91] = 16'h0000;
        mem[ 92] = 16'h0000;
        mem[ 93] = 16'h0000;
        mem[ 94] = 16'h0000;
        mem[ 95] = 16'h0000;
        mem[ 96] = 16'h0000;
        mem[ 97] = 16'h0000;
        mem[ 98] = 16'h0000;
        mem[ 99] = 16'h0000;
        mem[100] = 16'h0000;
        mem[101] = 16'h0000;
        mem[102] = 16'h0000;
        mem[103] = 16'h0000;
        mem[104] = 16'h0000;
        mem[105] = 16'h0000;
        mem[106] = 16'h0000;
        mem[107] = 16'h0000;
        mem[108] = 16'h0000;
        mem[109] = 16'h0000;
        mem[110] = 16'h0000;
        mem[111] = 16'h0000;
        mem[112] = 16'h0000;
        mem[113] = 16'h0000;
        mem[114] = 16'h0000;
        mem[115] = 16'h0000;
        mem[116] = 16'h0000;
        mem[117] = 16'h0000;
        mem[118] = 16'h0000;
        mem[119] = 16'h0000;
        mem[120] = 16'h0000;
        mem[121] = 16'h0000;
        mem[122] = 16'h0000;
        mem[123] = 16'h0000;
        mem[124] = 16'h0000;
        mem[125] = 16'h0000;
        mem[126] = 16'h0000;
        mem[127] = 16'h0000;
        mem[128] = 16'h0000;
        mem[129] = 16'h0000;
        mem[130] = 16'h0000;
        mem[131] = 16'h0000;
        mem[132] = 16'h0000;
        mem[133] = 16'h0000;
        mem[134] = 16'h0000;
        mem[135] = 16'h0000;
        mem[136] = 16'h0000;
        mem[137] = 16'h0000;
        mem[138] = 16'h0000;
        mem[139] = 16'h0000;
        mem[140] = 16'h0000;
        mem[141] = 16'h0000;
        mem[142] = 16'h0000;
        mem[143] = 16'h0000;
        mem[144] = 16'h0000;
        mem[145] = 16'h0000;
        mem[146] = 16'h0000;
        mem[147] = 16'h0000;
        mem[148] = 16'h0000;
        mem[149] = 16'h0000;
        mem[150] = 16'h0000;
        mem[151] = 16'h0000;
        mem[152] = 16'h0000;
        mem[153] = 16'h0000;
        mem[154] = 16'h0000;
        mem[155] = 16'h0000;
        mem[156] = 16'h0000;
        mem[157] = 16'h0000;
        mem[158] = 16'h0000;
        mem[159] = 16'h0000;
        mem[160] = 16'h0000;
        mem[161] = 16'h0000;
        mem[162] = 16'h0000;
        mem[163] = 16'h0000;
        mem[164] = 16'h0000;
        mem[165] = 16'h0000;
        mem[166] = 16'h0000;
        mem[167] = 16'h0000;
        mem[168] = 16'h0000;
        mem[169] = 16'h0000;
        mem[170] = 16'h0000;
        mem[171] = 16'h0000;
        mem[172] = 16'h0000;
        mem[173] = 16'h0000;
        mem[174] = 16'h0000;
        mem[175] = 16'h0000;
        mem[176] = 16'h0000;
        mem[177] = 16'h0000;
        mem[178] = 16'h0000;
        mem[179] = 16'h0000;
        mem[180] = 16'h0000;
        mem[181] = 16'h0000;
        mem[182] = 16'h0000;
        mem[183] = 16'h0000;
        mem[184] = 16'h0000;
        mem[185] = 16'h0000;
        mem[186] = 16'h0000;
        mem[187] = 16'h0000;
        mem[188] = 16'h0000;
        mem[189] = 16'h0000;
        mem[190] = 16'h0000;
        mem[191] = 16'h0000;
        mem[192] = 16'h0000;
        mem[193] = 16'h0000;
        mem[194] = 16'h0000;
        mem[195] = 16'h0000;
        mem[196] = 16'h0000;
        mem[197] = 16'h0000;
        mem[198] = 16'h0000;
        mem[199] = 16'h0000;
        mem[200] = 16'h0000;
        mem[201] = 16'h0000;
        mem[202] = 16'h0000;
        mem[203] = 16'h0000;
        mem[204] = 16'h0000;
        mem[205] = 16'h0000;
        mem[206] = 16'h0000;
        mem[207] = 16'h0000;
        mem[208] = 16'h0000;
        mem[209] = 16'h0000;
        mem[210] = 16'h0000;
        mem[211] = 16'h0000;
        mem[212] = 16'h0000;
        mem[213] = 16'h0000;
        mem[214] = 16'h0000;
        mem[215] = 16'h0000;
        mem[216] = 16'h0000;
        mem[217] = 16'h0000;
        mem[218] = 16'h0000;
        mem[219] = 16'h0000;
        mem[220] = 16'h0000;
        mem[221] = 16'h0000;
        mem[222] = 16'h0000;
        mem[223] = 16'h0000;
        mem[224] = 16'h0000;
        mem[225] = 16'h0000;
        mem[226] = 16'h0000;
        mem[227] = 16'h0000;
        mem[228] = 16'h0000;
        mem[229] = 16'h0000;
        mem[230] = 16'h0000;
        mem[231] = 16'h0000;
        mem[232] = 16'h0000;
        mem[233] = 16'h0000;
        mem[234] = 16'h0000;
        mem[235] = 16'h0000;
        mem[236] = 16'h0000;
        mem[237] = 16'h0000;
        mem[238] = 16'h0000;
        mem[239] = 16'h0000;
        mem[240] = 16'h0000;
        mem[241] = 16'h0000;
        mem[242] = 16'h0000;
        mem[243] = 16'h0000;
        mem[244] = 16'h0000;
        mem[245] = 16'h0000;
        mem[246] = 16'h0000;
        mem[247] = 16'h0000;
        mem[248] = 16'h0000;
        mem[249] = 16'h0000;
        mem[250] = 16'h0000;
        mem[251] = 16'h0000;
        mem[252] = 16'h0000;
        mem[253] = 16'h0000;
        mem[254] = 16'h0000;
        mem[255] = 16'h0000;
    end

    genvar g;
    generate
        for (g = 0; g < NUM_CHANNELS; g = g + 1) begin : ports
            assign dout[g] = mem[addr[g]];
        end
    endgenerate

    wire _unused = &{1'b0, clk};
endmodule

module data_ram #(
    parameter ADDR_BITS = 8,
    parameter DATA_BITS = 8,
    parameter NUM_CHANNELS = 4
) (
    input wire clk,
    input wire [ADDR_BITS-1:0] addr [NUM_CHANNELS-1:0],
    input wire [NUM_CHANNELS-1:0] we,
    input wire [DATA_BITS-1:0] din [NUM_CHANNELS-1:0],
    output wire [DATA_BITS-1:0] dout [NUM_CHANNELS-1:0],
    input wire [ADDR_BITS-1:0] dbg_addr,
    output wire [DATA_BITS-1:0] dbg_dout
);
    // Stay in ALM registers: never promote this to block RAM (multi-we is not a
    // legal single M10K port map). `ramstyle="logic"` is the portable hint; avoid
    // invalid altera_attribute names (Quartus rejects some .qsf-only settings in HDL).
    (* ramstyle = "logic" *)
    reg [DATA_BITS-1:0] mem [0:(1<<ADDR_BITS)-1];

    initial begin
        mem[  0] = 8'h00;
        mem[  1] = 8'h00;
        mem[  2] = 8'h00;
        mem[  3] = 8'h00;
        mem[  4] = 8'h00;
        mem[  5] = 8'h00;
        mem[  6] = 8'h00;
        mem[  7] = 8'h00;
        mem[  8] = 8'h00;
        mem[  9] = 8'h00;
        mem[ 10] = 8'h00;
        mem[ 11] = 8'h00;
        mem[ 12] = 8'h00;
        mem[ 13] = 8'h00;
        mem[ 14] = 8'h00;
        mem[ 15] = 8'h00;
        mem[ 16] = 8'h00;
        mem[ 17] = 8'h00;
        mem[ 18] = 8'h00;
        mem[ 19] = 8'h00;
        mem[ 20] = 8'h00;
        mem[ 21] = 8'h00;
        mem[ 22] = 8'h00;
        mem[ 23] = 8'h00;
        mem[ 24] = 8'h00;
        mem[ 25] = 8'h00;
        mem[ 26] = 8'h00;
        mem[ 27] = 8'h00;
        mem[ 28] = 8'h00;
        mem[ 29] = 8'h00;
        mem[ 30] = 8'h00;
        mem[ 31] = 8'h00;
        mem[ 32] = 8'h00;
        mem[ 33] = 8'h00;
        mem[ 34] = 8'h00;
        mem[ 35] = 8'h00;
        mem[ 36] = 8'h00;
        mem[ 37] = 8'h00;
        mem[ 38] = 8'h00;
        mem[ 39] = 8'h00;
        mem[ 40] = 8'h00;
        mem[ 41] = 8'h00;
        mem[ 42] = 8'h00;
        mem[ 43] = 8'h00;
        mem[ 44] = 8'h00;
        mem[ 45] = 8'h00;
        mem[ 46] = 8'h00;
        mem[ 47] = 8'h00;
        mem[ 48] = 8'h00;
        mem[ 49] = 8'h00;
        mem[ 50] = 8'h00;
        mem[ 51] = 8'h00;
        mem[ 52] = 8'h00;
        mem[ 53] = 8'h00;
        mem[ 54] = 8'h00;
        mem[ 55] = 8'h00;
        mem[ 56] = 8'h00;
        mem[ 57] = 8'h00;
        mem[ 58] = 8'h00;
        mem[ 59] = 8'h00;
        mem[ 60] = 8'h00;
        mem[ 61] = 8'h00;
        mem[ 62] = 8'h00;
        mem[ 63] = 8'h00;
        mem[ 64] = 8'h00;
        mem[ 65] = 8'h00;
        mem[ 66] = 8'h00;
        mem[ 67] = 8'h00;
        mem[ 68] = 8'h00;
        mem[ 69] = 8'h00;
        mem[ 70] = 8'h00;
        mem[ 71] = 8'h00;
        mem[ 72] = 8'h00;
        mem[ 73] = 8'h00;
        mem[ 74] = 8'h00;
        mem[ 75] = 8'h00;
        mem[ 76] = 8'h00;
        mem[ 77] = 8'h00;
        mem[ 78] = 8'h00;
        mem[ 79] = 8'h00;
        mem[ 80] = 8'h00;
        mem[ 81] = 8'h00;
        mem[ 82] = 8'h00;
        mem[ 83] = 8'h00;
        mem[ 84] = 8'h00;
        mem[ 85] = 8'h00;
        mem[ 86] = 8'h00;
        mem[ 87] = 8'h00;
        mem[ 88] = 8'h00;
        mem[ 89] = 8'h00;
        mem[ 90] = 8'h00;
        mem[ 91] = 8'h00;
        mem[ 92] = 8'h00;
        mem[ 93] = 8'h00;
        mem[ 94] = 8'h00;
        mem[ 95] = 8'h00;
        mem[ 96] = 8'h00;
        mem[ 97] = 8'h00;
        mem[ 98] = 8'h00;
        mem[ 99] = 8'h00;
        mem[100] = 8'h00;
        mem[101] = 8'h00;
        mem[102] = 8'h00;
        mem[103] = 8'h00;
        mem[104] = 8'h00;
        mem[105] = 8'h00;
        mem[106] = 8'h00;
        mem[107] = 8'h00;
        mem[108] = 8'h00;
        mem[109] = 8'h00;
        mem[110] = 8'h00;
        mem[111] = 8'h00;
        mem[112] = 8'h00;
        mem[113] = 8'h00;
        mem[114] = 8'h00;
        mem[115] = 8'h00;
        mem[116] = 8'h00;
        mem[117] = 8'h00;
        mem[118] = 8'h00;
        mem[119] = 8'h00;
        mem[120] = 8'h00;
        mem[121] = 8'h00;
        mem[122] = 8'h00;
        mem[123] = 8'h00;
        mem[124] = 8'h00;
        mem[125] = 8'h00;
        mem[126] = 8'h00;
        mem[127] = 8'h00;
        mem[128] = 8'h00;
        mem[129] = 8'h00;
        mem[130] = 8'h00;
        mem[131] = 8'h00;
        mem[132] = 8'h00;
        mem[133] = 8'h00;
        mem[134] = 8'h00;
        mem[135] = 8'h00;
        mem[136] = 8'h00;
        mem[137] = 8'h00;
        mem[138] = 8'h00;
        mem[139] = 8'h00;
        mem[140] = 8'h00;
        mem[141] = 8'h00;
        mem[142] = 8'h00;
        mem[143] = 8'h00;
        mem[144] = 8'h00;
        mem[145] = 8'h00;
        mem[146] = 8'h00;
        mem[147] = 8'h00;
        mem[148] = 8'h00;
        mem[149] = 8'h00;
        mem[150] = 8'h00;
        mem[151] = 8'h00;
        mem[152] = 8'h00;
        mem[153] = 8'h00;
        mem[154] = 8'h00;
        mem[155] = 8'h00;
        mem[156] = 8'h00;
        mem[157] = 8'h00;
        mem[158] = 8'h00;
        mem[159] = 8'h00;
        mem[160] = 8'h00;
        mem[161] = 8'h00;
        mem[162] = 8'h00;
        mem[163] = 8'h00;
        mem[164] = 8'h00;
        mem[165] = 8'h00;
        mem[166] = 8'h00;
        mem[167] = 8'h00;
        mem[168] = 8'h00;
        mem[169] = 8'h00;
        mem[170] = 8'h00;
        mem[171] = 8'h00;
        mem[172] = 8'h00;
        mem[173] = 8'h00;
        mem[174] = 8'h00;
        mem[175] = 8'h00;
        mem[176] = 8'h00;
        mem[177] = 8'h00;
        mem[178] = 8'h00;
        mem[179] = 8'h00;
        mem[180] = 8'h00;
        mem[181] = 8'h00;
        mem[182] = 8'h00;
        mem[183] = 8'h00;
        mem[184] = 8'h00;
        mem[185] = 8'h00;
        mem[186] = 8'h00;
        mem[187] = 8'h00;
        mem[188] = 8'h00;
        mem[189] = 8'h00;
        mem[190] = 8'h00;
        mem[191] = 8'h00;
        mem[192] = 8'h00;
        mem[193] = 8'h00;
        mem[194] = 8'h00;
        mem[195] = 8'h00;
        mem[196] = 8'h00;
        mem[197] = 8'h00;
        mem[198] = 8'h00;
        mem[199] = 8'h00;
        mem[200] = 8'h00;
        mem[201] = 8'h00;
        mem[202] = 8'h00;
        mem[203] = 8'h00;
        mem[204] = 8'h00;
        mem[205] = 8'h00;
        mem[206] = 8'h00;
        mem[207] = 8'h00;
        mem[208] = 8'h00;
        mem[209] = 8'h00;
        mem[210] = 8'h00;
        mem[211] = 8'h00;
        mem[212] = 8'h00;
        mem[213] = 8'h00;
        mem[214] = 8'h00;
        mem[215] = 8'h00;
        mem[216] = 8'h00;
        mem[217] = 8'h00;
        mem[218] = 8'h00;
        mem[219] = 8'h00;
        mem[220] = 8'h00;
        mem[221] = 8'h00;
        mem[222] = 8'h00;
        mem[223] = 8'h00;
        mem[224] = 8'h00;
        mem[225] = 8'h00;
        mem[226] = 8'h00;
        mem[227] = 8'h00;
        mem[228] = 8'h00;
        mem[229] = 8'h00;
        mem[230] = 8'h00;
        mem[231] = 8'h00;
        mem[232] = 8'h00;
        mem[233] = 8'h00;
        mem[234] = 8'h00;
        mem[235] = 8'h00;
        mem[236] = 8'h00;
        mem[237] = 8'h00;
        mem[238] = 8'h00;
        mem[239] = 8'h00;
        mem[240] = 8'h00;
        mem[241] = 8'h00;
        mem[242] = 8'h00;
        mem[243] = 8'h00;
        mem[244] = 8'h00;
        mem[245] = 8'h00;
        mem[246] = 8'h00;
        mem[247] = 8'h00;
        mem[248] = 8'h00;
        mem[249] = 8'h00;
        mem[250] = 8'h00;
        mem[251] = 8'h00;
        mem[252] = 8'h00;
        mem[253] = 8'h00;
        mem[254] = 8'h00;
        mem[255] = 8'h00;
    end

    always @(posedge clk) begin
        if (we[0]) mem[addr[0]] <= din[0];
        if (we[1]) mem[addr[1]] <= din[1];
        if (we[2]) mem[addr[2]] <= din[2];
        if (we[3]) mem[addr[3]] <= din[3];
    end

    genvar g;
    generate
        for (g = 0; g < NUM_CHANNELS; g = g + 1) begin : ports
            assign dout[g] = mem[addr[g]];
        end
    endgenerate

    assign dbg_dout = mem[dbg_addr];
endmodule
